### ISSUE TITLE
Bot Commands

### ISSUE THREAD

**Issue by thomann061** [landonp1203/yahoo-fantasy-bot#2]
Are there a list of commands to query matchups, transactions, etc.  Thanks.

**Comment by landonp1203** [comment]
I am actually working on this right now.  I should have it done in the mid-week time.

**Comment by landonp1203** [comment]
Done for now with commands.  If anymore are to be added, this will be reopened.

**Comment by thomann061** [comment]
I am trying to enter './fantasy help' with no response.

**Comment by landonp1203** [comment]
@thomann061 Sorry I didn't see this my notifications are off on Github for some reason.

So I found a nasty issue with Heroku that was an oversight on my part.  On the free tier dyno of Heroku, if the dyno does not get any activity within 30min, the dyno shuts down.  If you also have a worker dyno set up as well, like this project does, that goes to sleep too.

I've been working on migrating the bot over to a single web dyno and that pings itself so that it stays awake.  I also assume that your web dyno was shut down as per the instructions in the README.  With the bot commands, the web dyno actually has to be on, so that is my fault.

I will need to both update the README, as well as the project so that it runs on a web-dyno.  Not proud of doing this just because I'd rather dedicate the bot itself to a worker and receiving commands to a web dyno.

**Comment by landonp1203** [comment]
@thomann061 I updated the bot, check out the bottom of the README for the updated instructions.  Cheers!

**Comment by landonp1203** [comment]
Found out that the bot is not pinging the server so it is still shutting down.  Looking for fix.

**Comment by landonp1203** [comment]
7702c29 should fix this

**Comment by landonp1203** [comment]
Scratch that, 7702c29  now keeps the server alive with a heartbeat every 5 minutes.

**Comment by landonp1203** [comment]
Okay Heroku is giving me a headache, now its freaking out about DB connections -_-
