### ISSUE TITLE
Issues running bot

### ISSUE THREAD

**Issue by parthka** [landonp1203/yahoo-fantasy-bot#33]
Bot errors out, checked Yahoo/GroupMe connections. 

2019-09-09T23:11:44.994895+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=sia-ff-gm.herokuapp.com request_id=c14762bc-30b4-4d5b-ae3f-6a9cc1a0e55b fwd="24.125.169.225" dyno= connect= service= status=503 bytes= protocol=https

**Comment by landonp1203** [comment]
This means that your web dyno was off when you tried to hit the `Open App` button.  If you were trying to authenticate with Yahoo, the web dyno must be on first, then click the `Open App`, authenticate, then shut it off after and keep the bot dyno on.  Otherwise your bot will sleep if the web dyno is on for more than 30min without activity.  Sounds like this relates to #28?

**Comment by Jonath22b** [comment]
Hey @landonp1203 had the issue with the bot sleeping last night even with Web dyno off and only bot dyno on, I had to turn the bot dyno off and then on again to get notifications again.

**Comment by landonp1203** [comment]
When you checked the logs, do you remember what they said?

**Comment by landonp1203** [comment]
Closing since no further information given.
