### ISSUE TITLE
Trade Alert does not show if it was Approved or Disallowed. 

### ISSUE THREAD

**Issue by nzbordie** [landonp1203/yahoo-fantasy-bot#47]
Does the API have different trade options? 

Trade Accepted
Trade Declined
Trade Approved
Trade Disallowed

I think having these options would be awesome.

**Comment by nzbordie** [comment]
I brought this up because when I disallowed a trade. The bot shouted 'Trade Alert' which wasn't the truth

**Comment by landonp1203** [comment]
I would like this feature too, but Yahoo doesn't give that type of granularity in their API digging into it the way the bot uses the API.  Yahoo doesn't tell whether or not the trade was allowed or not, thus the bot thinks it happens since it cannot determine it.  I apologize.  If I find something in the API that they have added, I will re-open this.
